# Code generated by dev-tool; DO NOT EDIT.
ARG REPO_URL

FROM ${REPO_URL}golang:1.22-alpine3.19

ENV GO111MODULE=on
ENV GOFLAGS="-mod=vendor"

WORKDIR /go/src/service
COPY . .

WORKDIR /go/src/service/cmd/app
RUN GOOS=linux CGO_ENABLED=0 go build -o service -buildvcs=false

WORKDIR /go/src/service

FROM ${REPO_URL}alpine:3.12.3

RUN apk --no-cache add ca-certificates tzdata 

WORKDIR /
USER nobody

COPY --from=0 /go/src/service/cmd/app/service .

CMD ["/service"]
