// Package httpservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/flypay/go-kit/v4 version (devel) DO NOT EDIT.
package httpservice

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// User defines model for User.
type User struct {
	Dob         string `json:"dob"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	SlackHandle string `json:"slackHandle"`
	UserId      string `json:"userId"`
}

// AddUserJSONRequestBody defines body for AddUser for application/json ContentType.
type AddUserJSONRequestBody = User
