// Package httpservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/flypay/go-kit/v4 version v4.114.0 DO NOT EDIT.
package httpservice

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// User defines model for User.
type User struct {
	Dob         *time.Time          `json:"dob,omitempty"`
	FirstName   *string             `json:"first_name,omitempty"`
	LastName    *string             `json:"last_name,omitempty"`
	SlackHandle *openapi_types.File `json:"slack_handle,omitempty"`
	UserId      *int64              `json:"user_id,omitempty"`
}

// AddUserJSONRequestBody defines body for AddUser for application/json ContentType.
type AddUserJSONRequestBody = User
